### ISSUE TITLE
How to setup and run?

### ISSUE THREAD

**Issue by ChefMC** [delay/sveltekit-auth#8]
How to setup and run this scaffold? I imported GitHub project, made changes in `.env` file and issued command `npm run dev`, but getting this:

```
"C:\Program Files\nodejs\npm.cmd" run dev

> sveltekit-auth@0.0.1 dev
> vite dev


Forced re-optimization of dependencies

  VITE v5.0.10  ready in 987 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
05:10:58 [vite] Error when evaluating SSR module /src/lib/server/database/drizzle.ts:
|- Error: SASL: SCRAM-SERVER-FINAL-MESSAGE: server signature is missing
    at D:\Dev\IdeaProjects\SaaS_SvelteKit\sveltekit-auth\node_modules\pg-pool\index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async eval (D:\Dev\IdeaProjects\SaaS_SvelteKit\sveltekit-auth\src\lib\server\database\drizzle.ts:8:1)
    at async instantiateModule (file:///D:/Dev/IdeaProjects/SaaS_SvelteKit/sveltekit-auth/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:50506:9)

05:10:58 [vite] Error when evaluating SSR module /src/lib/server/lucia.ts: failed to import "/src/lib/server/database/drizzle.ts"
|- Error: SASL: SCRAM-SERVER-FINAL-MESSAGE: server signature is missing
    at D:\Dev\IdeaProjects\SaaS_SvelteKit\sveltekit-auth\node_modules\pg-pool\index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async eval (D:\Dev\IdeaProjects\SaaS_SvelteKit\sveltekit-auth\src\lib\server\database\drizzle.ts:8:1)
    at async instantiateModule (file:///D:/Dev/IdeaProjects/SaaS_SvelteKit/sveltekit-auth/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:50506:9)

05:10:58 [vite] Error when evaluating SSR module /src/hooks.server.ts: failed to import "/src/lib/server/lucia.ts"
|- Error: SASL: SCRAM-SERVER-FINAL-MESSAGE: server signature is missing
    at D:\Dev\IdeaProjects\SaaS_SvelteKit\sveltekit-auth\node_modules\pg-pool\index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async eval (D:\Dev\IdeaProjects\SaaS_SvelteKit\sveltekit-auth\src\lib\server\database\drizzle.ts:8:1)
    at async instantiateModule (file:///D:/Dev/IdeaProjects/SaaS_SvelteKit/sveltekit-auth/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:50506:9)

Error: SASL: SCRAM-SERVER-FINAL-MESSAGE: server signature is missing
    at D:\Dev\IdeaProjects\SaaS_SvelteKit\sveltekit-auth\node_modules\pg-pool\index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async eval (D:\Dev\IdeaProjects\SaaS_SvelteKit\sveltekit-auth\src\lib\server\database\drizzle.ts:8:1)
    at async instantiateModule (file:///D:/Dev/IdeaProjects/SaaS_SvelteKit/sveltekit-auth/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:50506:9)
Error: SASL: SCRAM-SERVER-FINAL-MESSAGE: server signature is missing
    at D:\Dev\IdeaProjects\SaaS_SvelteKit\sveltekit-auth\node_modules\pg-pool\index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async eval (D:\Dev\IdeaProjects\SaaS_SvelteKit\sveltekit-auth\src\lib\server\database\drizzle.ts:8:1)
    at async instantiateModule (file:///D:/Dev/IdeaProjects/SaaS_SvelteKit/sveltekit-auth/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:50506:9)
```

**Comment by delay** [comment]
I am not sure.  I don’t use windows and don’t know how it runs on it.  Sorry…

**Comment by ChefMC** [comment]
Why do you think it's OS issue? You don't provided any info about setup at all. Which Node.js version to use? Which steps installation requires? Which command running app?

**Comment by ChefMC** [comment]
I switched to 20.12.2 and seems like it works, but how to create database tables (migrations)? E.g. users table, etc.

**Comment by ChefMC** [comment]
Found command `npm run migrate`, tables are created. But should I perform any additional actions? Thank you

**Comment by delay** [comment]
npm run generate
npm run migrate
